name: first-pipe
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "First-job"
    runs-on: ubuntu-latest
    steps:
      - name: "First Action"
        run: echo "Primeira ação sendo executada às" $(date)
      - name: "Second Action"
        run: echo "Criado o primeiro workflow"
  second-job:
    name: "Second-job"
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: "Definindo versão 22.18.0 para NodeJS"
        uses: actions/setup-node@v4
        with:
           node-version: '22.18.0'
      - name: "Validando versão NodeJS"
        run: node --version

